# Base information
baseURL = "https://samrobbins.uk"
languageCode = "en-gb"
title = "Sam Robbins"
theme = "tailwind-developer-website"
googleAnalytics = "G-VMYNYEWJCJ"
pygmentsCodeFences = true
pygmentsUseClasses = true
sectionPagesMenu = "main"

[params]
home = "Home"
# Meta data
description = "The website of Sam Robbins, 2nd Year Computer Science Student at Durham University"
author = "Sam Robbins"


[markup]
  [markup.goldmark]
      [markup.goldmark.extensions]
        footnote = true
      [markup.goldmark.renderer]
       unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    tabWidth = 4

